/*
 * This source file was generated by the Gradle 'init' task
 */
package lab3;

import javax.swing.*;

public class App {
    public static void main(String[] args) {
        // JFrame frame = new JFrame("GUI");
        // frame.setSize(300, 300);
        // frame.setResizable(false);
        // frame.setVisible(true);
    }
}
